name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
        with:
          url: https://yaronltest15.jfrog.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yaronltest15.jfrog.io/docker/${{ github.repository }}:latest
